=== aym-frikha/neutron-map/ValidMakerDB/Schema/GenericService.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="GenericService">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Description" type="xs:string"/>
                <xs:element name="Transactional" type="xs:boolean"/>
                <xs:element name="Priority" type="xs:integer"/>
                <xs:element name="Domain" type="xs:string"/>
                <xs:element name="ServiceTree">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Node" type="GenNode" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="GenNode">
        <xs:sequence>
            <xs:element minOccurs="0" name="BaseParent" nillable="true">
                <xs:complexType>
                    <xs:attribute name="href" type="xs:string"/>
                </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Parameters">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" name="Node" type="GenNode"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Children">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" name="Node" type="GenNode"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute default="null" name="CimRef" type="xs:string"/>
        <xs:attribute default="true" name="known" type="xs:boolean"/>
        <xs:attribute default="false" name="parameter" type="xs:boolean"/>
        <xs:attribute default="0" name="uid" type="xs:long"/>
        <xs:attribute name="cardinality">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="11"/>
                    <xs:enumeration value="01"/>
                    <xs:enumeration value="0N"/>
                    <xs:enumeration value="1N"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute default="false" name="shadow" type="xs:boolean"/>
    </xs:complexType>
</xs:schema>

=== aym-frikha/neutron-map/ValidMakerDB/Services_Supported_old/GenericService - trunk-allow.xml
<?xml version="1.0"?>
<GenericService xmlns:ns="http://NamespaceTest.com/NodeType"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/C:/Program%20Files/validmaker/Data/Schema/GenericService.xsd" name="trunk-allow" >
  <Description>
  </Description>
<Priority>False</Priority>
<Domain>L2</Domain>
  <ServiceTree>
    <Node name="interface" CimRef="" uid="1">
      <BaseParent href="" />
      <Children>
        <Node name="trunk vlan" CimRef="" uid="2"/>
	</Children>
    </Node>
  </ServiceTree>
</GenericService>

=== aym-frikha/neutron-map/ValidMakerDB/Services_Supported/trunk-allow.xml
<?xml version="1.0"?>
<GenericService xmlns:ns="http://NamespaceTest.com/NodeType"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../Schema/GenericService.xsd" name="trunk-allow" >
  <Description>
  </Description>
<Transactional>false</Transactional>
<Priority>2</Priority>
<Domain>L2</Domain>
  <ServiceTree>
    <Node name="interface" CimRef="" uid="1">
      <BaseParent href="" />
      <Children>
        <Node name="switchport access" CimRef="" uid="2">
                <Parameters>
                    <Node name="vlan" CimRef="" uid="4"></Node>
                </Parameters>
          </Node>
        <Node name="switchport mode" CimRef="" uid="2"/>
        <Node name="switchport trunk" CimRef="" uid="3">
            <Parameters>
                <Node name="vlan" CimRef="" uid="4"/>
            </Parameters>
        </Node>
	</Children>
    </Node>
  </ServiceTree>
</GenericService>

=== aym-frikha/neutron-map/ValidMakerDB/Services_Supported_old/GenericService - Vlan.xml
<?xml version="1.0"?>
<GenericService xmlns:ns="http://NamespaceTest.com/NodeType"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/C:/Program%20Files/validmaker/Data/Schema/GenericService.xsd" name="Vlan">
  <Description />
<Priority>2</Priority>
<Domain>L2</Domain>
  <ServiceTree>
    <Node name="interface" uid="1">
      <BaseParent />
      <Children>
        <Node name="mode" uid="2">
          <BaseParent xsi:nil="true" />
        </Node>
        <Node name="vlan" uid="3">
          <BaseParent xsi:nil="true" />
        </Node>
      </Children>
    </Node>
  </ServiceTree>
</GenericService>

=== aym-frikha/neutron-map/ValidMakerDB/Services_Supported/vpls.xml
<?xml version="1.0" standalone="yes"?>
<GenericService xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../Schema/GenericService.xsd" name="vpls">
  <Description>
  </Description>
<Transactional>false</Transactional>
<Priority>2</Priority>
<Domain>L3</Domain>
  <ServiceTree>
    <Node name="l2 vfi" CimRef="" uid="1">
      <BaseParent href="" />
      <Children>
        <Node name="vpn id" CimRef="" uid="2" />
        <Node name="neighbor" CimRef="" uid="3" cardinality="1N"/>
      </Children>
    </Node>
    <Node name="interface" CimRef="" uid="4">
      <BaseParent href="" />
      <Children>
        <Node name="ip address" CimRef="" uid="5" />
      </Children>
    </Node>
    
   <Node name="interface vlan" CimRef="" uid="8">
      <BaseParent href="" />
      <Children>
        <Node name="xconnect vfi" CimRef="" uid="9" />
      </Children>
    </Node>
  </ServiceTree>
</GenericService>

=== aym-frikha/neutron-map/ValidMakerDB/Services_Supported/eompls_int.xml
<?xml version="1.0"?>
<GenericService xmlns:ns="http://NamespaceTest.com/NodeType"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../Schema/GenericService.xsd" name="eompls_int">
  <Description />
<Transactional>false</Transactional>
<Priority>1</Priority>
<Domain>L3</Domain>
  <ServiceTree>
    <Node name="interface" uid="1">
      <BaseParent />
      <Children>
        <Node name="ip address" uid="2">
          <BaseParent xsi:nil="true" />
        </Node>
        <Node name="ip ospf network" uid="3">
          <BaseParent xsi:nil="true" />
        </Node>
      </Children>
    </Node>
    <Node name="interface" uid="4">
      <BaseParent />
      <Children>
        <Node name="mpls ip" uid="5">
          <BaseParent xsi:nil="true" />
        </Node>
      </Children>
    </Node>
  </ServiceTree>
</GenericService>

=== aym-frikha/neutron-map/ValidMakerDB/Services_Supported/eompls_ext.xml
<?xml version="1.0"?>
<GenericService xmlns:ns="http://NamespaceTest.com/NodeType"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../Schema/GenericService.xsd" name="eompls_ext">
  <Description />
<Transactional>false</Transactional>
<Priority>1</Priority>
<Domain>L3</Domain>
  <ServiceTree>
    <Node name="interface" uid="1">
      <BaseParent />
      <Children>
        <Node name="no ip address" uid="2">
          <BaseParent xsi:nil="true" />
        </Node>
          <Node name="duplex auto" uid="2">
          <BaseParent xsi:nil="true" />
        </Node>
          <Node name="speed auto" uid="2">
          <BaseParent xsi:nil="true" />
        </Node>
        <Node name="xconnect" uid="3">
          <BaseParent xsi:nil="true" />
            <Parameters>
              <Node name="vcid" uid="4" parameter="true" shadow="true">
                <BaseParent xsi:nil="true" />
              </Node>
              <Node name="encapsulation" uid="5" parameter="true">
                <BaseParent xsi:nil="true" />
              </Node>
            </Parameters>
        </Node>
      </Children>
    </Node>
    <Node name="router ospf" uid="6">
      <BaseParent />
      <Children>
        <Node name="log-adjacency-changes" uid="7">
          <BaseParent xsi:nil="true" />
        </Node>
          <Node name="passive-interface" uid="8">
          <BaseParent xsi:nil="true" />
        </Node>
        <Node name="network" uid="9">
          <BaseParent xsi:nil="true" />
            <Parameters>
              <Node name="area" uid="10">
                <BaseParent xsi:nil="true" />
              </Node>
            </Parameters>
        </Node>
      </Children>
    </Node>
  </ServiceTree>
</GenericService>

=== aym-frikha/neutron-map/ValidMakerDB/Services_Supported/vlan.xml
<?xml version="1.0"?>
<GenericService xmlns:ns="http://NamespaceTest.com/NodeType"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../Schema/GenericService.xsd" name="vlan">
  <Description />
<Transactional>false</Transactional>
<Priority>2</Priority>
<Domain>L2</Domain>
  <ServiceTree>
    <Node name="interface" uid="1">
      <BaseParent />
      <Children>
        <Node name="switchport" uid="2">
          <BaseParent xsi:nil="true" />
            <Parameters>
                <Node name="vlan" uid="3">
                    <BaseParent xsi:nil="true" />
                </Node>
            </Parameters>
        </Node>
      </Children>
    </Node>
  </ServiceTree>
</GenericService>
