=== aym-frikha/neutron-map/ValidMakerDB/Schema/Rule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Rule">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Description" type="xs:string"/>
                <xs:element name="Conditions">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="Condition"
                                type="LogOperation"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Actions">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="Action"
                                type="LogOperation"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="LogOperation">
        <xs:sequence>
            <xs:element default="NONE" name="LogicalOp" type="xs:string"/>
            <xs:element name="Negated" type="xs:boolean"/>
            <xs:element name="Operation" type="xs:string"/>
            <xs:element name="LeftTree" type="xs:integer"/>
            <xs:element name="LeftOperand" type="Operand"> </xs:element>
            <xs:element name="RightTree" type="xs:integer"/>
            <xs:element name="RightOperand" type="Operand"> </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="RuleNode">
        <xs:sequence>
            <xs:element name="ServiceRef" type="xs:string"/>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="GUID" type="xs:long"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Operand">
        <xs:choice>
            <xs:element name="Node" nillable="false" type="RuleNode" minOccurs="0"/>
            <xs:element name="Value" type="xs:string" minOccurs="0"/>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== aym-frikha/neutron-map/ValidMakerDB/Services_Supported_old/Rule - VPLS Rule02.xml
<?xml version="1.0" standalone="yes"?>
<Rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/C:/Program%20Files/validmaker/Data/Schema/Rule.xsd" name="VPLS Rule02">
  <Description>dans la meme arbre la valeur de "xconnect vfi" doit etre egale a "l2 vfi"</Description>
  <Conditions/>
  <Actions>
    <Action>
      <LogicalOp>NONE</LogicalOp>
      <Negated>false</Negated>
      <Operation>NodeValueEqual</Operation>
      <LeftTree>1</LeftTree>
      <LeftOperand>
        <Node>
          <ServiceRef>VPLS</ServiceRef>
          <Name>xconnect vfi</Name>
          <GUID>9</GUID>
        </Node>
      </LeftOperand>
      <RightTree>1</RightTree>
      <RightOperand>
        <Node>
          <ServiceRef>VPLS</ServiceRef>
          <Name>l2 vfi</Name>
          <GUID>1</GUID>
        </Node>
      </RightOperand>
    </Action>
  </Actions>
</Rule>

=== aym-frikha/neutron-map/ValidMakerDB/Rules_old/VPLS Rule03.xml
<?xml version="1.0" standalone="yes"?>
<Rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/C:/Program%20Files/validmaker/Data/Schema/Rule.xsd" name="VPLS Rule03">
  <Description>dans la meme arbre la valeur de "interface vlan" doit etre egale a "trunk vlan"</Description>
  <Conditions/>
  <Actions>
    <Action>
      <LogicalOp>NONE</LogicalOp>
      <Negated>false</Negated>
      <Operation>NodeValueEqual</Operation>
      <LeftTree>1</LeftTree>
      <LeftOperand>
        <Node>
          <ServiceRef>VPLS</ServiceRef>
          <Name>interface vlan</Name>
          <GUID>8</GUID>
        </Node>
      </LeftOperand>
      <RightTree>1</RightTree>
      <RightOperand>
        <Node>
          <ServiceRef>trunk-allow</ServiceRef>
          <Name>vlan</Name>
          <GUID>4</GUID>
        </Node>
      </RightOperand>
    </Action>
  </Actions>
</Rule>

=== aym-frikha/neutron-map/ValidMakerDB/Services_Supported_old/Rule - VPLS Rule01.xml
<?xml version="1.0" standalone="yes"?>
<Rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/C:/Program%20Files/validmaker/Data/Schema/Rule.xsd" name="VPLS Rule01">
  <Description>dans deux arbre differents si si l2 vfi sont egaux alors la valeur de neighbor est egale a l'adresse ip de l'interface loopback0</Description>
  <Conditions>
    <Condition>
      <LogicalOp>NONE</LogicalOp>
      <Negated>false</Negated>
      <Operation>NodeValueEqual</Operation>
      <LeftTree>1</LeftTree>
      <LeftOperand>
        <Node>
          <ServiceRef>VPLS</ServiceRef>
          <Name>l2 vfi</Name>
          <GUID>1</GUID>
        </Node>
      </LeftOperand>
      <RightTree>2</RightTree>
      <RightOperand>
        <Node>
          <ServiceRef>VPLS</ServiceRef>
          <Name>l2 vfi</Name>
          <GUID>1</GUID>
        </Node>
      </RightOperand>
    </Condition>
  </Conditions>
  <Actions>
    <Action>
      <LogicalOp>NONE</LogicalOp>
      <Negated>false</Negated>
      <Operation>NodeValueEqual</Operation>
      <LeftTree>1</LeftTree>
      <LeftOperand>
        <Node>
          <ServiceRef>VPLS</ServiceRef>
          <Name>neighbor</Name>
          <GUID>3</GUID>
        </Node>
      </LeftOperand>
      <RightTree>2</RightTree>
      <RightOperand>
        <Node>
          <ServiceRef>VPLS</ServiceRef>
          <Name>ip address</Name>
          <GUID>5</GUID>
        </Node>
      </RightOperand>
    </Action>
  </Actions>
</Rule>

=== aym-frikha/neutron-map/ValidMakerDB/Rules_old/VPLS Rule04.xml
<?xml version="1.0" standalone="yes"?>
<Rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/C:/Program%20Files/validmaker/Data/Schema/Rule.xsd" name="VPLS Rule04">
  <Description>dans deux arbre differents si "l2 vfi" sont egaux alors la valeur de "vpn id" seront egaux</Description>
  <Conditions>
    <Condition>
      <LogicalOp>NONE</LogicalOp>
      <Negated>false</Negated>
      <Operation>NodeValueEqual</Operation>
      <LeftTree>1</LeftTree>
      <LeftOperand>
        <Node>
          <ServiceRef>VPLS</ServiceRef>
          <Name>l2 vfi</Name>
          <GUID>1</GUID>
        </Node>
      </LeftOperand>
      <RightTree>2</RightTree>
      <RightOperand>
        <Node>
          <ServiceRef>VPLS</ServiceRef>
          <Name>l2 vfi</Name>
          <GUID>1</GUID>
        </Node>
      </RightOperand>
    </Condition>
  </Conditions>
  <Actions>
    <Action>
      <LogicalOp>NONE</LogicalOp>
      <Negated>false</Negated>
      <Operation>NodeValueEqual</Operation>
      <LeftTree>1</LeftTree>
      <LeftOperand>
        <Node>
          <ServiceRef>VPLS</ServiceRef>
          <Name>vpn id</Name>
          <GUID>2</GUID>
        </Node>
      </LeftOperand>
      <RightTree>2</RightTree>
      <RightOperand>
        <Node>
          <ServiceRef>VPLS</ServiceRef>
          <Name>vpn id</Name>
          <GUID>2</GUID>
        </Node>
      </RightOperand>
    </Action>
  </Actions>
</Rule>

=== aym-frikha/neutron-map/ValidMakerDB/Rules/eompls_equal.xml
<?xml version="1.0" standalone="yes"?>
<Rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../Schema/Rule.xsd" name="eompls_equal">
  <Description>dans deux arbre differents il faut que xconnect est egale a l'adresse ip de l'interface loopback0</Description>
  <Conditions>
    <Condition>
      <LogicalOp>NONE</LogicalOp>
      <Negated>false</Negated>
      <Operation>NodeValueEqual</Operation>
      <LeftTree>1</LeftTree>
      <LeftOperand>
        <Node>
          <ServiceRef>eompls_ext</ServiceRef>
          <Name>xconnect</Name>
          <GUID>3</GUID>
        </Node>
      </LeftOperand>
      <RightTree>2</RightTree>
      <RightOperand>
        <Node>
          <ServiceRef>eompls_int</ServiceRef>
          <Name>ip address</Name>
          <GUID>2</GUID>
        </Node>
      </RightOperand>
    </Condition>
  </Conditions>
  <Actions>
  </Actions>
</Rule>

=== aym-frikha/neutron-map/ValidMakerDB/Rule - trunk-allow Rule01.xml
<?xml version="1.0" standalone="yes"?>
<Rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/C:/Program%20Files/validmaker/Data/Schema/Rule.xsd" name="trunk-allow Rule01">
  <Description>In two different trees, if the values of 'ip vrf' nodes match, then the data in the branches of those nodes must match as well. </Description>
  <Conditions>
    <Condition>
      <LogicalOp>NONE</LogicalOp>
      <Negated>false</Negated>
      <Operation>NodeDataEqual</Operation>
      <LeftTree>1</LeftTree>
      <LeftOperand>
        <Node>
          <ServiceRef>trunk-allow</ServiceRef>
          <Name>mode</Name>
          <GUID>2</GUID>
        </Node>
      </LeftOperand>
      <RightTree>2</RightTree>
      <RightOperand>
        <Node>
          <ServiceRef>trunk-allow</ServiceRef>
          <Name>mode</Name>
          <GUID>2</GUID>
        </Node>
      </RightOperand>
    </Condition>
  </Conditions>
  <Actions>
    <Action>
      <LogicalOp>NONE</LogicalOp>
      <Negated>false</Negated>
      <Operation>NodeDataEqual</Operation>
      <LeftTree>1</LeftTree>
      <LeftOperand>
        <Node>
          <ServiceRef>trunk-allow</ServiceRef>
          <Name>mode</Name>
          <GUID>2</GUID>
        </Node>
      </LeftOperand>
      <RightTree>2</RightTree>
      <RightOperand>
        <Node>
          <ServiceRef>trunk-allow</ServiceRef>
          <Name>mode</Name>
          <GUID>2</GUID>
        </Node>
      </RightOperand>
    </Action>
  </Actions>
</Rule>
